### ISSUE TITLE
AWS Lambda nodejs 8.10 runtime is EOL December 31, 2019

### ISSUE THREAD

**Issue by valters** [verzac/typescript-aws-sam#4]
Hi,

I was reviewing the state of the art for developing with TypeScript, and noticed your sample project (which currently seems most up-to-date of them all). But it still is now out-of-date because it references nodejs8.10 runtime, which is already EOL by AWS, per https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html policy.

I was wondering if you would care to refresh it to use nodejs12.x runtime, update the dependencies (possibly build with new hot TypeScript version), etc? I am looking to do this myself, but I am not familiar with the npm world, and each error I encounter looks more daunting than the next.

**Comment by verzac** [comment]
Hi valters,

Thanks for chucking an issue!

Ah, I thought I upgraded the runtime to Node 10 last year; must've forgotten to do it for this repo.

I'll update the runtime soon, since we can't create Node 8 functions anymore :)

I'm personally not super keen on updating dependencies because it's an endless race to keep the dependencies up-to-date. _As long as it still works_, I can still demonstrate how you can make TS work in Lambda.

That being said:
1. **Updating dependencies** in this project's package.json shouldn't break anything, because all of these dependencies are independent of each other. I've been updating dependencies in my other projects (which are based on this one) and nothing has been broken so far. You can update it by following this guide: https://bytearcher.com/articles/using-npm-update-and-npm-outdated-to-update-dependencies#going-for-bigger-update-with-latest-tag, or by running `npm update`.
2. **Updating Typescript**; same as above, really. TypeScript should be mostly backward compatible with previous versions of itself, so you shouldn't have any problem upgrading your TypeScript version (through `npm update typescript`).

Feel free to chuck a PR if you're up for it though! I don't mind people contributing to this repo :)

Let me know if you have any other questions!

PS: My other project which is based on this is https://github.com/verzac/news-neutrality-scraper, but since it's still a WIP I haven't added a README to it yet.

**Comment by verzac** [comment]
Fixed it in the latest commit, forgot to make a PR and to reference this issue...

TL:DR I bumped the dependencies up and the runtime version to nodejs12.x.

Thanks for chucking in a PR. Feel free to reopen if you have any questions!

**Comment by valters** [comment]
Thank you, you are very kind!
